version: "3.0"
services:

  docker-mysql:
    image: mysql:8.0.25
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=referral-store
    ports:
      - "3306:3306"
    volumes:
      - ./sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql

#  referral-store:
#    image: referral-store
#    restart: on-failure
#    depends_on:
#      - docker-mysql
#    ports:
#      - "8082:8082"
#      - "8442:8442"
#    environment:
#      - DATABASE_HOST=docker-mysql
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=root
#      - DATABASE_NAME=referral-store
#      - DATABASE_PORT=3306
